name: Build CI

on:
  push:
    branches: [ "main" ]
  pull_request:
    branches: [ "main" ]

jobs:
  build:

    runs-on: ubuntu-latest

    steps:
    - uses: actions/checkout@v4
    - name: Build
      run: tools/install-build-deps --ui
    - name: Build ui
      run: ui/build
    - name: Move
      run: mkdir -p save&&mv ui/dist ui/save&&mv ui/out ui/save
    - name: Save
      uses: LarchLiu/actions-save-files@v1.0.3
      with:
        github_token: ${{ secrets.GITHUB_TOKEN }}
        publish_branch: publish
        publish_dir: ui/save

    
