name: Build CI

on:
  push:
    branches: [ "main" ]
  pull_request:
    branches: [ "main" ]

jobs:
  build:

    runs-on: ubuntu-latest

    steps:
    - uses: actions/checkout@v4
    - name: Build
      run: tools/install-build-deps --ui
    - name: Save
      uses: LarchLiu/actions-save-files@v1.0.3
      with:
        github_token: ${{ secrets.GITHUB_TOKEN }}
        publish_dir: .

    
