name: Build CI

on:
  push:
    branches: [ "main" ]
  pull_request:
    branches: [ "main" ]

jobs:
  build:

    runs-on: ubuntu-latest

    steps:
    - uses: actions/checkout@v4
    - name: Build
      run: tools/install-build-deps --ui
    - name: Build ui
      run: ui/build
    - name: Move
      run: mv ui/out ui/save
    - name: Save
      uses: actions/upload-artifact@v4.5.0
      with:
        name: save
        path: ui/save

    
